In [ ]:
#q1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?
#ans. numpy is referred to as numerical python. it stores the data in the numpy array. the advantage of numpy is that its computation is very fast because it contains homogeneous data.it is stored in continuous memory location.




Object `operations` not found.


q2Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

ans. np.mean() takes in account masks, so compute the mean only over unmasked values and np.average() do not take in account masks so compute the average over the whole set of data.

q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.


ans 1. by using np.flip()
2. using a list slicing method

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
res = np.flip(arr)
print ("final array",str(res))

final array [5 4 3 2 1]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print("arr", str(arr))
print ("type of arr", type(arr))
res = arr[::-1]
print("final array" , str(res))

arr [1 2 3 4]
type of arr <class 'numpy.ndarray'>
final array [4 3 2 1]


q4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
ans.we can determine the data type of elements present in numpy array by using dtype attribute.

In [ ]:
import numpy as np
arr = np.array([[5,6,7],[8,9,0]])
arr.dtype

dtype('int64')

q5  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ans. An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape , which is a tuple of N non-negative integers that specify the sizes of each dimension.
The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

q6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

ans NumPy arrays provide a significant speed advantage over python lists. in numpy operations are applied to all elements in an array without the need for explicit loops in Python.

q7  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

ans If the axis is set to 0, it works as vstack and if the axis is 1, it works as hstack

In [ ]:
#hstack
import numpy as np
A = np.ones((2,2),int)
B= np.zeros((2,4),int)
print("A:",A,"\n","B:",B)

A: [[1 1]
 [1 1]] 
 B: [[0 0 0 0]
 [0 0 0 0]]


In [ ]:
hstack = np.hstack((A,B))
print(hstack)

[[1 1 0 0 0 0]
 [1 1 0 0 0 0]]


In [ ]:
#vstack
A = np.ones((3,4))
B = np.zeros((2,4))
print("A:",A,"\n","B:",B)

A: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 B: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
vstack = np.vstack((A,B))
print(vstack)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

ans flipud() specialized for vertical flipping and numpy. fliplr() specialized for horizontal flipping

q9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits

ans.array_split() function allows uneven splits and handles any remaining elements. Efficiency: While numpy. split() divides the array into equal-sized sub-arrays, numpy. array_split() can handle uneven splits.

q10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

ans. broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language. It does this without making needless copies of data which leads to efficient algorithm implementations.

#practical questions
1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
arr = np.random.randint(1,100, (3,3))
arr

array([[90, 93,  9],
       [97, 15,  3],
       [ 8, 80,  7]])

In [ ]:
arr.T

array([[90, 97,  8],
       [93, 15, 80],
       [ 9,  3,  7]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
l = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(l)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
arr = np.random.rand(4,4)
arr

array([[0.21678148, 0.67734238, 0.52026398, 0.71678011],
       [0.76764244, 0.04102926, 0.96553185, 0.0946837 ],
       [0.67181835, 0.52211141, 0.01212244, 0.83792272],
       [0.99247883, 0.49627463, 0.98657187, 0.47887523]])

In [ ]:
arr = np.pad(arr, pad_width=1, mode='constant',
               constant_values=0)
print(arr)


[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.21678148 0.67734238 0.52026398 0.71678011
  0.         0.        ]
 [0.         0.         0.76764244 0.04102926 0.96553185 0.0946837
  0.         0.        ]
 [0.         0.         0.67181835 0.52211141 0.01212244 0.83792272
  0.         0.        ]
 [0.         0.         0.99247883 0.49627463 0.98657187 0.47887523
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.




In [ ]:
array = np.arange(10, 61, 5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
arr = ["python", "numpy", "pandas"]
arr = np.array(arr)
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [3]:
import numpy as np
r = (["sandy" , "krish" , "manya"])

x = np.char.join(" ", r)
print (x)

['s a n d y' 'k r i s h' 'm a n y a']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [4]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [5]:
arr2

array([[2, 2, 2],
       [1, 1, 2],
       [1, 2, 1]])

In [6]:
arr1 + arr2

array([[3, 4, 4],
       [2, 2, 4],
       [2, 3, 2]])

In [7]:
arr1 - arr2

array([[-1,  0,  0],
       [ 0,  0,  0],
       [ 0, -1,  0]])

In [8]:
arr1* arr2

array([[2, 4, 4],
       [1, 1, 4],
       [1, 2, 1]])

In [9]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [1. , 1. , 1. ],
       [1. , 0.5, 1. ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [14]:
import numpy as np
r = np.eye(5)
r

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr2 = np.diag(r)
arr2

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [18]:
rand_vals = np.random.randint(0, 1001, size=100)
rand_vals

array([1000,  548,  103,  362,  668,  556,  571,  825,   89,  550,  413,
        308,  904,  373,  239,  731,  970,  731,  305,    3,   27,  160,
        337,  888,  934,  249,  996,  802,  938,   57,  964,  752,  483,
        826,  316,  432,  878,  208,  382,  898,  824,   80,  249,  570,
        780,  565,  947,  754,  514,  922,  287,    2,  352,  746,  745,
        406,  342,  244,  891,   97,  687,  288,  371,  991,  876,  936,
        280,  673,  855,  715,  887,  160,  885,  388,  843,  319,  372,
        926,  327,   30,  718,  937,    1,  499,  391,  256,  436,  837,
        515,  823,  711,  212,  721,  937,  605,  989,  935,  626,    6,
        928])

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
